Flags for client methods, support for weak clients
NickvisionApps/MPVSharp pull request #10
Opened 2023-07-29 20:44 UTC by fsobolev

Closes #4 
Closes #3

2023-07-29 20:49 UTC, nlogozzo requested changes
Can you fix the examples too?

Edit: just saw the new commit :)

2023-07-29 20:49 UTC, nlogozzo commented on Nickvision.MPVSharp/Internal/MPVClient.cs
> +    public nint Handle { get; }
{ get; init; }

2023-07-29 20:51 UTC, fsobolev commented on Nickvision.MPVSharp/Internal/MPVClient.cs
> +    public nint Handle { get; }
isn't it redundant?

2023-07-29 20:51 UTC, nlogozzo commented on Nickvision.MPVSharp/Internal/MPVClient.cs
> +    public nint Handle { get; }
No because I believe it resorts to { private set; } by default

2023-07-29 20:52 UTC, fsobolev commented on Nickvision.MPVSharp/Internal/MPVClient.cs
> +    public nint Handle { get; }
ah okay

2023-07-29 20:57 UTC, nlogozzo commented
Will merge when I get home from work and release next ver :)

2023-07-29 20:57 UTC, nlogozzo approved these changes

2023-07-30 02:29 UTC, merged

2023-07-30 02:34 UTC, nlogozzo commented
https://www.nuget.org/packages/Nickvision.MPVSharp/2023.7.1