Windows support
NickvisionApps/MPVSharp pull request #11
Opened 2023-08-31 15:58 UTC by fsobolev

![image](https://github.com/NickvisionApps/MPVSharp/assets/117388856/0822b1a6-6fa7-4e11-836f-8144241bb839)

For some reason MPV can't find yt-dlp in PATH, so I had to place the binary in config dir (`%APPDATA%/mpv`) for the OpenGL example to work, and also yt-dlp seems to be very slow on Windows (it takes *a lot* of time to load a video from youtube, but in WSL it's fine). Other than that the example works as expected.

Closes #6 

TODO:
- [ ] Update docs
- [ ] Create `MPVSharp.Bundled` package with libmpv built-in, this will be primary usable on Windows, I think to avoid licensing issues we have to build libmpv in LGPL mode that [disables some features on Linux](https://github.com/mpv-player/mpv/blob/master/Copyright). And I need some hints how to implement this.

2023-09-01 00:34 UTC, fsobolev commented
Okay, seems like I made working package with bundled libmpv. Dll file is from [this repo](https://github.com/shinchiro/mpv-winbuild-cmake), I used latest release. I didn't find anything similar pre-built for Linux, and building this myself seems to be very time-consuming, and considering that installing and adding libmpv to linux packages is much easier than doing the same on windows, I think it's fine to have Bundled package windows-only, it only really preferred there IMO. The library here seems to be complete, with GPL parts, so I set license for Bundled package to be GPL too (I'm not sure that copyleft really works here, but I think it's better to assume it does).

For testing I modified OpenGL example's csproj to have this:

```
  <PropertyGroup> 
<RestoreSources>$(RestoreSources);../../Nickvision.MPVSharp/bin/Debug;../../Nickvision.MPVSharp.Bundled/bin/Debug;https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.7.7" />
    <PackageReference Include="Nickvision.MPVSharp.Bundled" Version="2023.7.2" />
  </ItemGroup>
```

And it worked.

I first tried to have ProjectReference instead of PackageReference in Bundled, but it was causing NU1102 error when build the example for some reason.

2023-09-02 03:59 UTC, nlogozzo requested changes
Let's use `ProjectReference` here that way when we build the nuget for `Bundled` we don't need to wait for the regular one to upload to nuget then update the Package ver then build the Bundled nuget...

Everything else looks great tho!

2023-09-02 03:59 UTC, nlogozzo commented on Nickvision.MPVSharp.Bundled/Nickvision.MPVSharp.Bundled.csproj
> +    <PackageReference Include="Nickvision.MPVSharp" Version="2023.7.2" />
```xml
<ProjectReference Include="..\Nickvision.MPVSharp\Nickvision.MPVSharp.csproj" />
```

2023-09-02 10:22 UTC, fsobolev commented on Nickvision.MPVSharp.Bundled/Nickvision.MPVSharp.Bundled.csproj
> +    <PackageReference Include="Nickvision.MPVSharp" Version="2023.7.2" />
okay, let me try again, I will try to find why I get NU1102 error when using ProjectReference

2023-09-02 11:11 UTC, fsobolev commented on Nickvision.MPVSharp.Bundled/Nickvision.MPVSharp.Bundled.csproj
> +    <PackageReference Include="Nickvision.MPVSharp" Version="2023.7.2" />
Found why I was getting the error. It's because I was removing `../../Nickvision.MPVSharp/bin/Debug` in RestoreSources in example's csproj. When dotnet packs Bundled it doesn't include MPVSharp, but creates a dependency with matching version, so the difference between PackageReference and ProjectReference is that for ProjectReference we just don't need to specify a version.

https://stackoverflow.com/a/65803800
> By default, when you use ProjectReference to Reference Project A into Project B under new-sdk project, it actually views the Project A as a nuget dependency.

But this seems to not be a problem, looks like it will be possible to upload Bundled even without uploading MPVSharp (but the users will not be able to install it).
https://stackoverflow.com/a/70764466
> dotnet pack and nuget pack assume that you're going to also be packing each of those projects as packages as well, and writes the project reference as a package dependency at the same version of the dependent project package. So, if you pack projB @ v1.2.3 the package will have a dependency reference to projA @ v1.2.3. If you don't pack projA @ v1.2.3 or you don't publish that package (because maybe there weren't any changes to it), consumers of projB @ v1.2.3 will fail the install because nuget won't find projA @ v1.2.3.

2023-09-02 12:40 UTC, nlogozzo approved these changes

2023-09-03 02:53 UTC, merged